### ISSUE TITLE
Little spelling mistake in ru/part6

### ISSUE THREAD

**Issue by Scarboroid** [bagder/http2-explained#127]
6.5. Сжатие заголовков

Paragraph
Как я уже упоминал, в то время как число объектов на странице увеличивается, использование cookie и размер запросов также продолжают расти. Cookie также должны быть включены во все запросы, практически всегда одинаковые на протяжение множества запросов.

Need replace "на протяжени**е** множества запросов" to "на протяжени**и** множества запросов"

**Comment by vlet** [comment]
Thanks for correction. May you create pull request with fix?
