### ISSUE TITLE
Little mistake in ru/part12

### ISSUE THREAD

**Issue by Scarboroid** [bagder/http2-explained#128]
12.1. QUIC

Протокол QUIC (Quick UDP Internet Connections, Быстрые UDP Интернет Соединений) Гугла – это интересный эксперимент, проведённый в том же стиле, как и с SPDY. QUIC – это замена TCP + TLS + HTTP/2, реализованная поверх UDP.

"Быстрые UDP Интернет Соединений" replace to "Быстрые UDP интернет соединения"

**Comment by vlet** [comment]
Thanks. Same proposal as in #127
