### ISSUE TITLE
HTTP/2 is only supported over TSL in all major browser

### ISSUE THREAD

**Issue by atheedom** [bagder/http2-explained#142]
According to caniuse.com (http://caniuse.com/#search=http2) all major browsers will support HTTP/2 over TSL only. 

In part 5 (https://bagder.gitbooks.io/http2-explained/en/part5.html) it says that the Internet Explorer team has expressed that they will support insecure HTTP/2 upgrade path. This is no longer true as HTTP/2 is only supported over TLS for IE. The IE edge documentation supports this https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/networking-and-connectivity/HTTP2.

Thanks.

**Comment by bagder** [comment]
The fact remains that they did express their intention to implement support for HTTP/2 without requiring TLS, even if they've never provided such support. I suppose the paragraph should clarify that better. It was written a long time ago by now and it hasn't been updated since.

**Comment by bagder** [comment]
Thanks for the issue, I've now updated that section to be clearer.
