### ISSUE TITLE
5.3: Application-Layer Protocol Negotiation instead of Application Level Protocol Negotiation

### ISSUE THREAD

**Issue by saivlis** [bagder/http2-explained#18]
I think ALPN means *Application-Layer* Protocol Negotiation instead of *Application Level* Protocol Negotation. That is at least what [RFC 7301](https://tools.ietf.org/html/rfc7301) says.

By the way, thanks for that excellent summary.

**Comment by bagder** [comment]
Good catch, thanks a lot! Fixed now.
