### ISSUE TITLE
http2 support in browsers update

### ISSUE THREAD

**Issue by saravananmk** [bagder/http2-explained#191]
https://http2-explained.haxx.se/content/en/part8.html

Original:
```
[...]

There are several big browsers behind the roll-out. Representatives from
Firefox, Chrome, Safari, Internet Explorer and Opera have expressed they will
ship http2 capable browsers and they have shown working implementations.
```
Update:
All major browsers (e.g. Firefox, Chrome, Safari, Internet Explorer, Edge, Opera) now supports http2.

Ref: https://caniuse.com/#search=http%2F2

**Comment by bagder** [comment]
As mentioned in e3e7871e4b274752a6d65, I'll leave the section mostly as written in 2015.
