### ISSUE TITLE
{curl, libcurl} http2 enable status on linux

### ISSUE THREAD

**Issue by saravananmk** [bagder/http2-explained#194]
https://http2-explained.haxx.se/content/en/part11.html

Original:
```
[...]

Note that currently on linux curl and libcurl are not always delivered with
HTTP/2 protocol support enabled.
```
Does it still true? If not, this line need to be removed.

**Comment by bagder** [comment]
Yes it is and it will always be true. "not always" is very open ended...

**Comment by saravananmk** [comment]
Thanks for the clarifications.
