### ISSUE TITLE
Chrome extension for check http/2 server support

### ISSUE THREAD

**Issue by lucianojs** [bagder/http2-explained#20]
I suggest add mention a SPDY Indicator plugin for chrome for check if server has support at http/2

https://chrome.google.com/webstore/detail/spdy-indicator/mpbpobfflnpcgagjijhmgnchggcjblin

Has a similar plugin on Firefox but at the moment no has support at http/2

https://addons.mozilla.org/pt-BR/firefox/addon/spdy-indicator/

**Comment by bagder** [comment]
Thanks, it is indeed a good suggestion. I already use this plugin for Firefox:

I use this https://github.com/chengsun/moz-spdy-indicator

**Comment by bagder** [comment]
I've now added mentions of both of these in the version in git. Thanks!
