### ISSUE TITLE
4.1.1

### ISSUE THREAD

**Issue by laconic75** [bagder/http2-explained#22]
>The group is named HTTPbis where the “bis” part comes from the Latin adverb for "two".

I don't know much Latin, but "two" is an adjective in every language I know.

**Comment by bagder** [comment]
Thanks. I think I got that from http://en.wiktionary.org/wiki/bis#Latin ...

**Comment by laconic75** [comment]
OK that makes sense. Twice is the adverb and two is the adjective.

**Comment by bagder** [comment]
Cool. I'm adding a footnote with a link to that article just as a reference for future readers. Thanks!
