### ISSUE TITLE
Graph keys/labels

### ISSUE THREAD

**Issue by sbrickey** [bagder/http2-explained#23]
On page 6, the line graph (presumably showing objects/page and load size) includes no key to specifically state that it is the case.

Just for best practice and all.

**Comment by sbrickey** [comment]
Nor does it show the specific four years being addressed.

**Comment by bagder** [comment]
I'm not sure I understand. What "keys" isn't stated in the text above the graph? And it says "the last four years" there too.

Not saying the graph can't be improved, just that the info is there.

**Comment by sbrickey** [comment]
just something indicating color to purpose... just so that the graph can be understood without reading the paragraph of text describing it. (issue title says "keys/labels"... perhaps "legend" is better)

same reason for labeling the years.

**Comment by bagder** [comment]
Fair enough, I'll add details for the next revision. Thanks!
