### ISSUE TITLE
Concatenation

### ISSUE THREAD

**Issue by pquentin** [bagder/http2-explained#24]
> The annoyance to developers and the hoops everyone has to go through to do this is of course “just” pain for the humans involved and not seen in any performance numbers...

I'm not a native speaker but this sentence is difficult to understand. What is not seen in any performance numbers? The annoyance, I guess (after reading this sentence 10 times)? On my first read I understood that this trick did not improve performance.

Thanks for the book!

**Comment by bagder** [comment]
Thanks. I agree that it is a quirky. I will replace it with this simpler phrase instead: 

"This practice is of course mostly an inconvenience to the developers involved."

Sounds good?

**Comment by pquentin** [comment]
Yes, that's perfect, thanks!

**Comment by bagder** [comment]
Great, it'll show up in the next revision!
