### ISSUE TITLE
Typo in Section 11.4: Command line use

### ISSUE THREAD

**Issue by braxtone** [bagder/http2-explained#26]
Minor typo in the text of section 11.4 in the guide:
"To tell curl to use http2, either plain text or over TLS, you use the –http2 option (that is
“dash dash http2”). curl still defaults to HTTP/1.1 so the extra option is necessary when
you want http2."

The "-http2 option" bit contains only one hyphen/dash and should be changed to line up with the text

**Comment by bagder** [comment]
Thanks, fixed now!
