### ISSUE TITLE
Translate the book

### ISSUE THREAD

**Issue by pedrotcaraujo** [bagder/http2-explained#27]
Hi,
First of all, I would like to thanks, this book is very cool and helped me a lot. 

What do you think about to translate it for any languages?

Thanks!

**Comment by bagder** [comment]
I welcome translations! On the web site there's a link to the only translation done so far, Russian: http://daniel.haxx.se/http2/

You need to just keep in mind that the contents will likely continue to change slightly over time, even if the bulk of everything is probably fairly stable by now.
