### ISSUE TITLE
HTML version

### ISSUE THREAD

**Issue by bagder** [bagder/http2-explained#32]
Convert the ODF version into a HTML version that can be hosted on a single web page and in one page per chapter.

The work has began. I store the images in a separate directory (https://github.com/bagder/http2-explained/tree/master/images ) and I name the HTML directory after the language of the text (https://github.com/bagder/http2-explained/tree/master/en ) to allow more (future) versions in case translators want to use HTML too.

I have not considered CSS or other styling issues and I suck at that anyway.

**Comment by bagder** [comment]
Should we use Markdown instead?

**Comment by bclozel** [comment]
Why not try [asciidoctor](http://asciidoctor.org/) (or markdown, etc):

* natively supported by github (in previews and PRs)
* various backends available (HTML5, EPUB, docbook)
* solve the TOC and CSS issues for you

**Comment by markpapadakis** [comment]
+1 for markdown

**Comment by jeroenooms** [comment]
Markdown would be nice. John Macfarlane has a very fast c library [cmark](https://github.com/jgm/cmark) that will convert md to html, groff man or latex. Mix that in with a little css or latex template and you can render it almost on the fly.

**Comment by jeroenooms** [comment]
You might also want to look at [gitbooks](https://www.gitbook.com/) which makes it very easy to write books with git + markdown.

**Comment by bagder** [comment]
gitbooks looks interesting and I'll give that a shot. I think I'll start with first converting the entire thing into markdown. part 4 and 5 are already done this way now.

**Comment by bagder** [comment]
The pics are a bit crude in this version when browsed on github, but I'll leave them like that for now until I figure out how things work with gitbook.

**Comment by bagder** [comment]
It is now converted completely to markdown and pushed. Now I'm just having trouble getting gitbook to build it...

**Comment by bagder** [comment]
Got super quick and friendly help from the gitbook people and how you can see the first stumbling steps of the gitbook version at http://bagder.gitbooks.io/http2-explained/

**Comment by jeroenooms** [comment]
Very cool Daniel, this looks super neat already!

**Comment by bagder** [comment]
Now also readable on this URL: http://http2-explained.haxx.se/

Closing this issue now, but work will continue on making this version good-looking and then I'll announce it properly on the existing http2 explained site.
