### ISSUE TITLE
Incomplete Swedish translation

### ISSUE THREAD

**Issue by bagder** [bagder/http2-explained#48]
I started the Swedish translation, mostly to get the ball rolling. So far it is only part1 with a non-translated document history (I find that part more or less unnecessary to translate anyway since those versions never existed in Swedish).

**Comment by bagder** [comment]
part 1, 2, 13 and 14 now exist

**Comment by bittin** [comment]
http://http2-explained.haxx.se/content/sv/part9.html

"erbjudid" > erbjudit gissar jag ?

**Comment by bagder** [comment]
Thanks!
