### ISSUE TITLE
Spanish ready to be linked from web page

### ISSUE THREAD

**Issue by bagder** [bagder/http2-explained#55]
Hey @jabiinfante, I noticed your awesome merge in the is the 'es' subdir! Is the Spanish markdown version now "good enough" to be the one to link to from the web page at http://daniel.haxx.se/http2 ?

**Comment by jabiinfante** [comment]
It is as good as was the fodt file.
So i would say it is ;)

Maybe next time, I should open an issue before merging?

**Comment by bagder** [comment]
No biggie, just me being eager! =) Thanks for your work, will update the web page.
