### ISSUE TITLE
Minor french translation - chapter 5.4

### ISSUE THREAD

**Issue by wolruf** [bagder/http2-explained#56]
Chapter 5.4 title isn't translated:
5.4. http2 for http://
Could be "5.4. http2 et http://"

@machour if you have time to look at it

**Comment by machour** [comment]
Done. Kept "pour" for consistency with 5.2 naming.

**Comment by bagder** [comment]
Thanks a lot for your work on this, can I just ask you to follow the commit message style that I mention in the HOWTO-TRANSLATE.md. It is just to make it easier for us all to figure out what changes that concern us. Thanks!

**Comment by machour** [comment]
Will do so!
