### ISSUE TITLE
Gitbook - no page breaks in PDF

### ISSUE THREAD

**Issue by wolruf** [bagder/http2-explained#57]
Hi Daniel,
I see the Gitbook published book doesn't have any page breaks when converted to PDF. Not sure if it's a Gitbook limitation or a formatting issue.
Some people may like to download and print the PDF.

**Comment by machour** [comment]
@wolruf I do have a page break before every when I download the PDF from here: http://http2-explained.haxx.se/ (below the blue button). 

Works fine in Chrome PDF reader as well as OS X's Preview.
Which viewer are you using ?

**Comment by wolruf** [comment]
You're right, I can see the page breaks
