### ISSUE TITLE
Gitbook - search feature

### ISSUE THREAD

**Issue by wolruf** [bagder/http2-explained#58]
Hi Daniel,
Not sure if Gitbook is limited regarding the search feature.
I tried Chrome 45 and Safari on Mac, it doesn't highlight the term you search for, though it will limit the scope to the pages that have the searched for term.

-Olivier.

**Comment by bagder** [comment]
Sorry, but that's nothing I can do with the tools I have here. It sounds like a bug with gitbook. Of course one way is to get the PDF and search within that...
