### ISSUE TITLE
Mentioning colors for grayscale ebooks 

### ISSUE THREAD

**Issue by BjornW** [bagder/http2-explained#68]
## Problem 
Mentioning colours in text referring to diagrams displayed on grayscale ebook readers makes it hard to understand the diagram since the colours are indistinguishable.

## Solution 
Don't use colours to differentiate but use symbols or changes in line drawing. For instance a dotted line vs a connected line. This is easy to understand on a gray scale ereader (in my case an older Kindle).

## Details
In '2.4 Transfer sizes and number of objects' you're referring to specific colors: 

"It shows the growth of the total transfer size (in green) and the total number of requests used on average (in red) to serve the most popular web sites in the world, and how they have changed over the last four years."

ps: Thanks for sharing your knowledge!

**Comment by bagder** [comment]
Thanks! I added descriptive texts next to the two lines and I've pushed the new version now.

**Comment by BjornW** [comment]
Thanks for the quick response.
